### Dockerfile for the Simulator stack
FROM ubuntu:20.04

RUN  apt-get update  -y \
  && apt-get install -y software-properties-common \
  && add-apt-repository ppa:deadsnakes/ppa \
  && apt install python3.10 -y \
  && apt install python3-pip -y \
  && apt-get install openjdk-8-jdk -y 

COPY requirements.txt requirements.txt
RUN  pip install -r requirements.txt

COPY *.py .
COPY *.sh .
COPY default_data/ ./default_data/
COPY har/ ./har/
